### ISSUE TITLE
Samba module should have separate client and server install profiles

### ISSUE THREAD

**Issue by sctweedie** [fedora-modularity/f27-content-tracking#19]
f27 samba module currently has only the "default" profile; we should provide easy installation of either the client or server components.

**Comment by sgallagher** [comment]
We probably need the following profiles:
* `SMB File-Sharing Client` - smbclient and friends
* `SMB File-Sharing Server` - smbd and friends
* `Domain Client` - This might be winbind from samba or metapackages that pulls in SSSD's AD support. TBD.
* `Domain Controller`

**Comment by alexxa** [comment]
@sctweedie , @sgallagher In the latest Boltron-f27 I see all profiles mentioned in the previous comment, except ```Domain Controller```: 
```
Boltron-27-af42c9fea72e-0# dnf module info samba
Last metadata expiration check: 5:04:08 ago on Tue 31 Oct 2017 09:14:17 AM UTC.

Name             : samba
Stream           : master (default)
Version          : 20171024112243
Profiles         : client default domainclient server
Default profiles : default
Repo             : fedora-modular-server
Summary          : samba module
Description      : This samba module has been generated.
Artifacts        : avahi-0:0.7-5.module_8789fd86.x86_64
....
```

So will that be added or not?

**Comment by sgallagher** [comment]
@alexxa It's definitely missing but could be put there quite easily if we want to (all the packages are available). It would basically be adding this to the profiles:
```
    profiles:
        domaincontroller:
            description: Windows Domain Controller
            rpms:
                - libldb
                - libtdb
                - samba
                - samba-common
                - samba-common-libs
                - samba-common-tools
                - samba-dc
                - samba-libs
```

I can add and push that unless anyone disagrees. @sctweedie, @whitel , @KarstenHopp  ?
