### ISSUE TITLE
freeipa module should have separate client and server install profiles 

### ISSUE THREAD

**Issue by sctweedie** [fedora-modularity/f27-content-tracking#20]
f27 freeipa module currently has only the "default" profile; we should provide easy installation of either the client or server components.

**Comment by sgallagher** [comment]
We may want to have multiple profiles here, actually:
* `FreeIPA Client`
* `FreeIPA Domain Controller` - LDAP+KRB5+CA+NTP
* `FreeIPA DNS Server` - BIND
* `FreeIPA Integration with Active Directory` - The tools for creating a cross-realm trust with AD

**Comment by langdon** [comment]
@sgallagher @KarstenHopp is this done?

**Comment by sgallagher** [comment]
@whitel No, there is currently a single profile:
```
    profiles:
        default:
            description: A generated profile based on top-lvl package list.
            rpms:
                - freeipa-client
                - freeipa-client-common
                - freeipa-common
                - freeipa-desktop-profile
                - freeipa-python-compat
                - freeipa-server
                - freeipa-server-common
                - freeipa-server-dns
                - freeipa-server-trust-ad
```
